name: Generate RULE-SET

on:
  schedule:
    - cron: '0 6 * * *' # 每天凌晨 12 点运行
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Download domain list
      run: curl -o domains.txt https://big.oisd.nl/dnsmasq2

    - name: Install dependencies
      run: npm install

    - name: Generate RULE-SET
      run: node generateRuleSet.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add adblock_ruleset.txt
        git commit -m 'Update RULE-SET'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
