name: Generate RULE-SET

on:
  schedule:
    - cron: '0 6 * * *' # 每天早上 6 点运行
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Download domain list
      run: curl -o domains.txt https://example.com/domains.txt

    - name: Install dependencies
      run: npm install

    - name: Generate RULE-SET
      run: node generateRuleSet.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'Lycofuture'
        git config --global user.email 'hizcmua@163.com'
        git remote set-url origin https://Lycofuture:${{ secrets.GB_TOKEN }}@github.com/Lycofuture/AdGuard.git
        git add adblock_ruleset.txt
        git commit -m 'Update RULE-SET'
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
